# Mini-mixed assessment

+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Information                         | Note                                                                                                                                                                                                                                                                                                                                                                |
+=====================================+=====================================================================================================================================================================================================================================================================================================================================================================+
| Name                                | Mini-mixed assessment                                                                                                                                                                                                                                                                                                                                               |
+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Type (Main, Mini or Basket)         | Mini                                                                                                                                                                                                                                                                                                                                                                |
+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Value                               | 5% (Path A)                                                                                                                                                                                                                                                                                                                                                         |
|                                     |                                                                                                                                                                                                                                                                                                                                                                     |
|                                     | 0% (Path B)                                                                                                                                                                                                                                                                                                                                                         |
+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Due                                 | Wednesday, March 9, 2022; assessment window from 8:00 a.m. ET to 8:00 p.m. ET                                                                                                                                                                                                                                                                                       |
+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Submission instructions             | Submission: Via [Quercus quiz](https://q.utoronto.ca/courses/253305/quizzes/237353) (50 minutes, 1 attempt, no pausing) and [Markus](https://markus-ds.teach.cs.toronto.edu/) (10 percentage point penalty for not submitting required files)                                                                                                                       |
+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Accommodations and extension policy | In the case of a personal illness/emergency, a [declaration can be made,](https://forms.office.com/Pages/ResponsePage.aspx?id=JsKqeAMvTUuQN7RtVsVSEOKHUU3SzAJJhmOKjJhDWEpUNTFDSzhZTFlXUzVYMVlNM1FEUTRZMkVWOC4u) but must be submitted no more than 3 days after the due date. Extensions may be requested through the same form up to 48 hours before the due date. |
+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Instructions

#### How your grade is calculated

-   The 98% of your mini-mixed grade is based on your performance on the **timed** component.

-   2% of your grade is based on the correctness of your Rmd. There will be a student facing autotest you can run on your submissions to check if the objects required are there and appear to be mostly sensible (note, this doesn't guarantee in all cases that they are fully RIGHT, just that they passes the checks set up for this component).

-   If you do the timed component, but DON'T submit the appropriate Rmd and PDF to MarkUs by the end of the window, there is an **additional** 10 percentage point penalty.

    -   Note the file name requirements: `sta303-w22-mini-mixed.Rmd` and `sta303-w22-mini-mixed.pdf`.
    -   You can upload as many times as you like BEFORE the end of the window on Wednesday, so make sure you upload a 'safety' copy of your Rmd and PDF once you have started working on it.

#### Getting help

**Piazza** will be available until the start of the window. You may ask questions about the untimed component of the mini-mixed assessment, using the mini-mixed assessment tag.

**Tech office hours** will take the place of our usual class time on Wednesday. Use the usual link to join. Content questions will not be answered, but I recommend you aim to complete the timed component before/during these times as then I can provide timely assistance if there are any issues.

**Review materials:**

-   [Check out the LMM study guides your classmates have been making.](https://q.utoronto.ca/courses/253305/discussion_topics/1637653)

-   Asynchronous review versions of Team Up! activities

    -   [Module 1 (Intro, linear regression as common tests)](https://jupyter.utoronto.ca/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fsta303-bolton%2Fsta303-w22-activities&urlpath=shiny%2Fsta303-w22-activities%2Finst%2Ftutorials%2Fsta303_m1_teamup_asynch%2FSTA303_m1_teamup_synch.Rmd&branch=master)

    -   [Module 2 (Data wrangling, ethics, communication)](https://jupyter.utoronto.ca/user/4d5187e2-ccd2-4902-8663-8a8c9843584a/git-pull?repo=https%3A%2F%2Fgithub.com%2Fsta303-bolton%2Fsta303-w22-activities&urlpath=shiny%2Fsta303-w22-activities%2Finst%2Ftutorials%2Fsta303_m2_teamup_asynch%2FSTA303_m2_teamup_asynch.Rmd&branch=master)

    -   [Module 3 (Linear Mixed Models)](https://jupyter.utoronto.ca/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fsta303-bolton%2Fsta303-w22-activities&urlpath=shiny%2Fsta303-w22-activities%2Finst%2Ftutorials%2Fsta303_m3_teamup_asynch%2FSTA303_m3_teamup_asynch.Rmd&branch=master)

#### Academic integrity

Please respect all of the hard work you've done so far this year as you complete the following assessment of your learning by making sure that the work you do here is your own. Don't put your academic career at risk.

There will be a question at the beginning of the timed component that you should read carefully.

#### Untimed component

[JupyterHub pull link (look for `sta303-w22-mini-mixed`)](https://jupyter.utoronto.ca/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fsta303-bolton%2Fsta303-w22-mini-mixed&urlpath=rstudio%2F)

#### Timed component

The timed component will become available at 8:00 a.m. ET and remain available until 8:00 p.m. ET. You will have 50 minutes to complete it.

Before attempting the timed component you should work through the guided analysis in the untimed component. There will be questions related to these tasks.

You must also submit your .Rmd and.pdf of the guided analysis before the end of the assessment window (8:00 p.m. ET on Wednesday, March 9).

Must read before starting assessment:

-   I suggest you use Chrome or Firefox to access this quiz. I use Chrome to write and check the quizzes. Additionally, make sure your browser is up to date as out-of-date versions also cause issues.

    -   Possible 'hack' if images don't load: Sometimes, right-clicking the image that is failing to load, and opening it in a new tab or downloading it, will let you see the image.

-   This timed assessment is open book, so you are welcome to review the notes while completing it.

-   From the time you start, you will have either 50 minutes to complete the quiz or until 8:00 p.m. ET on Wednesday, March 9, whichever comes first.

-   You cannot pause the quiz once you start it.

-   Ensure you will have uninterrupted access to the internet and a quiet space to work for the duration of the test.

-   A desktop computer or laptop is preferable to a tablet or phone.

-   Make sure your device is plugged in or will definitely have sufficient charge for the period of the test.

-   The quiz will auto-submit any answers at the deadline.

-   You have one attempt.

-   You do not have to run code while doing this quiz, but you are allowed to if you would like to.

-   BE PREPARED. Have back-ups planned as we will not be accepting technical issues as a reason for not submitting.

-   Make sure you submit the .pdf and .Rmd of your untimed component before the end of the timed window, also.

-   Academic integrity: When you take this quiz, you will be asked to confirm that your behaviour during the assessment adheres to the Code of Behaviour on Academic Matters. READ THIS QUESTION CAREFULLY. You would be surprised how often students don't do this. An incorrect answer may result in a 0 on the mini-mixed. Show me you are really reading and paying attention.
