---
title: "STA303: Methods of Data Analysis II"
subtitle: "Course guide"
author: "Prof. Liza Bolton"
date: "Winter 2022"
site: bookdown::bookdown_site
documentclass: book
classoption: openany
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
geometry: margin=2cm
urlcolor: blue
description: "This is a course for STA303: Methods of Data Analysis II at the University of Toronto"
---

# How to use this course guide

Placeholder


## Communication policy reminder
## Intellectual property statement
### Tutoring companies
## Contributors

<!--chapter:end:index.Rmd-->


# Syllabus {#syllabus}

Placeholder


## Course information
### Course description
### Class times
### Materials
### Teaching team
#### **Instructor**
#### Head TA
#### Teaching assistants
## Land acknowledgment
## Prerequisites
## Course format and organization
## Learning objectives
## Textbooks
## Computing and minimum technical requirements
## Course outline
## Assessments
### Knowledge basket
## Hours expectations
## Marking concerns / regrade requests
## Missed work policies
### Exceptions
### IMPORTANT NOTES
## Communication policy
## Accommodations and accessibility
### Accessibility services
### Religious Accommodation
## Recognized study groups
## Meet to complete
## Feeling distressed?
## Intellectual property statement
## Academic integrity
### Plagiarism
### Specific advice on untimed assessments
### Rules for timed assessments (e.g., mixed assessments)
### NOTE: BE CAREFUL ABOUT PRIVATE TUTORING COMPANIES
## Course design principles
### Humans learn better 'little and often' but everyone is burnout from two years of a pandemic
### Writing is good for statisticians
### Course content is Accessible

<!--chapter:end:01-syllabus.Rmd-->


# Start here!

Placeholder


## Introductions
### Professor Liza Bolton, Instructor
### Amin Banihashemi, Head TA
## A few things to know upfront
### Students joining off the waitlist
## How this course works {#howthiscourseworks}
#### **In most modules there be will be:**
## Hours expectations
### Communication
## To do now

<!--chapter:end:02-starthere.Rmd-->


# (PART\*) Assessments overview {.unnumbered}

Placeholder


## Graduate student modification (1002H)

<!--chapter:end:03-assessments.Rmd-->


# Mini-portfolio

Placeholder


## General instructions
### Template
## Submission instructions
## Cover page
## Introduction
## Statistical skills sample
### Task 1: Setting up libraries
### Task 2: Visualizing the variance of a Binomial random variable for varying proportions
#### Objects that must be carefully assigned to pass autograding
### Task 3: Demonstrating frequentist confidence intervals as long-run probabilities of capturing a population parameter
#### Specific steps
#### Objects that must be carefully assigned to pass autograding
### Task 4: Investigating whether there is an association between cGPA and STA303/1002 students correctly answering a question on global poverty rates
#### Goal
#### Wrangling the data
#### Visualizing the data
#### Testing
## Writing sample
#### Prompt
#### Job add
##### Data Scientist (Remote)
#### LI-Remote
## Reflection
## Rubric

<!--chapter:end:04-mini-portfolio.Rmd-->


# Portfolio

Placeholder


## General instructions
### Template
## Submission instructions
## Cover page
## Introduction
## Statistical skills sample
### A note on time management. 
### Task 1: Setting up libraries and seed value
### Task 2a: Return to Statdew Valley: exploring sources of variance in a balanced experimental design (teaching and learning world)
#### Growing your (grandmother's) strawberry patch
#### Plotting the strawberry patch
#### Demonstrating calculation of sources of variance in a least-squares modelling context
##### Model formula
##### Objects to create (proof-read carefully for autograding)
###### Tibbles
###### Models
###### Numeric values
### Task 2b: Applying linear mixed models for the strawberry data (practical world)
#### Justification and interpreation
### Task 3a: Building a confidence interval interpreter
#### Specifications:
### Task 3b: Building a p value interpreter
#### Here is an EXAMPLE. This is not the answer. I DO NOT want to see this submitted as an answer.
### Task 3c: User instructions and disclaimer
#### Instructions
#### Disclaimer
### Task 4: Creating a reproducible example (reprex)
### Task 5: Simulating p values
#### Setting up simulated data
#### Calculating _p_ values
#### Q-Q plots
#### Conclusion and summary
## Writing sample
### Prompt
## Reflection
## Rubric

<!--chapter:end:05-portfolio.Rmd-->

# Mini-mixed assessment

+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Information**                     | **Note**                                                                                                                                                               |
+=====================================+========================================================================================================================================================================+
| Name                                | Mini-mixed assessment                                                                                                                                                         |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Type (Main, Mini or Basket)         | Mini                                                                                                                                                                   |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Value                               | 5% (Path A)                                                                                                                                                            |
|                                     |                                                                                                                                                                        |
|                                     | 0% (Path B)                                                                                                                                                            |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Due                                 | `r mini_mixed`                                                                                                                                                             |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Submission instruction              | Submission: Via Quercus quiz (50 minutes, 1 attempt, no pausing) and [Markus](`r markus`) (10 percentage point penalty for not submitting required files)                                              |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Accommodations and extension policy | In the case of a personal illness/emergency, a [declaration can be made](`r extension`), but must be submitted no more than 3 days after the due date. Extensions may be requested through the same form up to 48 hours before the due date. |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Instructions

To be announced.

<!--chapter:end:06-mini-mixed.Rmd-->

# Mixed assessment

+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Information**                     | **Note**                                                                                                                                                               |
+=====================================+========================================================================================================================================================================+
| Name                                | Mixed assessment                                                                                                                                                         |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Type (Main, Mini or Basket)         | Main                                                                                                                                                                   |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Value                               | 20% (Path A)                                                                                                                                                            |
|                                     |                                                                                                                                                                        |
|                                     | 25% (Path B)                                                                                                                                                            |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Due                                 | `r mixed`                                                                                                                                                             |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Submission instruction              | Submission: Via Quercus quiz (2 x 50 minute components, 1 attempt, no pausing) and [Markus](`r markus`) (10 percentage point penalty for not submitting required files)                                              |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Accommodations and extension policy | In the case of a personal illness/emergency, a [declaration can be made](`r extension`), but must be submitted no more than 3 days after the due date. Extensions may be requested through the same form up to 48 hours before the due date. |
+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Instructions



<!--chapter:end:07-mixed.Rmd-->

# Final project
| **Information**                     | **Note**                                                                                                                                              |
|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
| Name                                | Final project                                                                                                                                         |
| Type (Main, Mini or Basket)         | Main                                                                                                                                                  |
| Value                               | 45%                                                                                                                                                   |
| Due                                 | `r final_project`                                                                                                                                     |
| Submission instruction              | Submission: Via [Markus](`r markus`)                                                                                                            |
| Accommodations and extension policy | There are no routine extensions granted for the final project. In exceptional circumstances, you can work with your College Registrar and me on this. |

### Instructions

To be announced.

#### Project groups

You can work on your project alone or with up to __three__ other students (regardless of section) for a group of __four__ total students.

Groups will need to register a few weeks in advance of the deadline (date TBC).

There will be opportunities to meet others in the class through some of the activities planned, and closer to the deadline to register groups, I will make the Piazza "Search for Teammates!" area available.

<!--chapter:end:08-final-project.Rmd-->


# Knowledge basket overview

Placeholder


### Planning and tips
### Examples
#### Student A
#### Student B
#### Student C

<!--chapter:end:09-knowledge-basket-overview.Rmd-->


# Knowledge basket: Writing and peer feedback

Placeholder


## General instructions {#writinggeneral}
### Create phase
### Assess phase
### Reflect phase
### General instructions
## Module 1 writing task
### M1 Instructions
#### M1 Prompt
#### M1 Rubric
## Module 2 writing task
### M2 Instructions
#### M2 Prompt
##### M2 Reference
#### M2 Rubric
## Module 3 writing task
### M3 instructions
#### M3 prompt
##### Example from a *different* article: Modified from (Berlowitz et al., 2017):
##### Reference:                                                                                                                                                                                               Berlowitz, D. R., Foy, C. G., Kazis, L. E., Bolin, L. P., Conroy, M. B., Fitzpatrick, P., . . . Group, S. R. (2017). Effect of Intensive Blood-Pressure Treatment on Patient-Reported Outcomes. *N Engl J Med, 377*(8), 733-744. doi:10.1056/NEJMoa1611179                                                             
#### References for this prompt
#### M3 Rubric 

<!--chapter:end:10-knowledge-basket-writing.Rmd-->


# Knowledge basket: Professional development task

Placeholder


## Professional development proposal
### Instructions
### Submission requirements
### Rubric
### Checklist
### Things to keep in minds as you start working towards your professional development goal
### Example smart goal
#### Specific
#### Measurable
#### Attainable
#### Relevant
#### Time-bounded:
## Professional development evidence and reflection
### Templates
### Reflection and evidence components
#### Activity, alignment and lessons
##### Examples
##### Examples
##### Examples
#### Evidence
##### Examples
#### Timesheet
##### Examples
### Recommended structure
### Rubric

<!--chapter:end:11-knowledge-basket-pd.Rmd-->


# Knowledge basket: Other

Placeholder


## 'Getting to know you' survey
### Instructions
## Pre-knowledge check
### Instructions
#### Grade structure
### Workshop attendance
## Module check-ins
### Instructions
## Team Up! activities
## Graduate school info session
## Punctuation art
### Instructions
#### Prompt
#### Examples
#### Skills
#### Tips
#### Submission instructions
#### Rubric

<!--chapter:end:12-knowledge-basket-other.Rmd-->


# (PART\*) Modules {-}
# Module 1 {#m1}

Placeholder


## Learning checklist
## Instructor information
## Upward management tips
### Communicate using the tools your manager prefers  
### Write good emails (when emails are appropriate)
### Understand your manager's goals
### Demonstrate self-management and resilience while also asking for help and flagging problems early. 
## Recap of linear models
### Why model?
### Linear models 
### Linear regression assumptions
### What makes it a _linear_ model?
#### Linear
#### NOT linear
### Optional refresher reading
#### Brief discussion of assumptions with examples
#### Fitting linear models in R
#### Delicious mathematics
## The data for module 1
### Let's meet the penguins 
### The variables
## Common statistical tests as linear regression
### Introduction
#### Parametric
#### Non-parametric
#### Aside: But why are there two types of tests?
### One-sample t-test
#### Use case
#### Assumptions
#### Hypotheses
#### Example
#### Now as a linear model
#### Wilcoxon signed-rank test
#### Paired sample t-test and Wilcoxon matched pair
### Dummy variables
#### The matrices we use for linear regression
#### Getting our model matrix in R
###### [Unassessed aside] Why do we have to drop one of the levels?
### Two means 
#### Use case
#### Assumptions
#### Hypotheses
#### Example
#### Mann-Whitney U
### ANOVA
#### Use case
#### Assumptions
#### Hypotheses
#### Example
### Credits
## Reproducible examples (reprex)
### What is a reproducible example?
### Why should you care about creating reproducible examples?
#### Other things to know
### Watch the creator of the reprex package explain it
### Using reprexes on Piazza
## Reading strategy: previewing and skimming {#previewskim}
## Getting ahead on Module 2

<!--chapter:end:20-module1.Rmd-->


# Module 2 {#m2}

Placeholder


## Learning checklist
### Key functions
## Introduction to Module 2
## Readings for this module
### R for Data Science (+ story time)
### Common misconceptions about data analysis and statistics
### To predict and serve?
### Science isn't broken
## Data wrangling and visualization
### Tidy data
#### A bit of advice...and why we need **tidy** data
#### Rules of tidy data
#### Recognizing Tidy Data
#### Further reading on tidy data (optional)
### Student grades case study
#### Videos
## Ethical professional practice for statisticians
### Why should statisticians be ethical?
#### Relevant codes of conduct for statistical societies/associations in North America {#ethicscodes}
### Getting data
#### Confounding and study design
##### Confounders (i.e. confounding factors or confounding variables)
##### Designing studies to avoid confounding
##### Common study designs and how to recognize them
##### Causation from observational studies?
###### Bradford Hill criteria (not assessed)
#### Human research ethics
##### Principles of free and informed consent
###### Information
###### Comprehension
###### Voluntariness
#### Web scraping and APIs
##### What do you need to web scrape?
##### The Ethical Scraper
##### Terms and Conditions and Robots.txt
##### Robots.txt
##### Using an API
#### Indigenous data sovereignty
##### How can U of T students develop their knowledge?
#### Selection bias
##### Survivorship bias
### Analyzing data {#analyzingethics}
#### HARKing
#### Multiple testing problem
##### Correcting for multiple comparisons?
### Making decisions with data
#### Algorithmic bias
##### Proxy variables
#### Should algorithms be transparent?
## Statistical communication
### Prioritize statistical communication as part of your toolbox
#### What can statisticians learn about communication from Winston Churchill's mother's dinner conversation?
### What do statisticians usually *write*?
### Common report components
#### Brief overview (ONE of the following, not both)
##### Abstract (or summary)
###### 'Plain English' summaries 
##### Executive summary
#### Introduction {#introreport}
#### Data summary (optional)
#### Methods {#methodsreport}
#### Results {#resultsreport}
#### Conclusion/discussion {#concreport}
#### References {#referencesreport}
#### Appendices {#appreport}
#### Final notes on organization
### Paraphrasing
#### Example activity prompt
##### Sample partial/complete answers with overall gradings
###### Poor
###### Adequate
###### Excellent
#### How to think about paraphrasing?
##### Example using the Swales & Feak (2012) approach
#### References {#pararef}

<!--chapter:end:21-module2.Rmd-->


# Module 3 {#m3}

Placeholder


## Learning checklist
## Introduction
### How deep are we going on likelihoods?
#### Maximum likelihood review
#### Properties of maximum likelihood estimators
#### Suggested reading
### Model comparison more generally
##### References
## Correlated data 
### Reading
### Key vocabulary
## Statdew Valley interactive
### Welcome to Statdew Valley!
### Optional: Create your 16 bit character
### Task 1: Tomatoes (part 1)
#### Plot the tomat-ah dat-ah
#### The WRONG approach: fixed effects only
##### Model
#### Let's try some models: Part 1
#### Summary
### Task 1: Tomatoes (part 2)
#### The RIGHT approach: mixed effects
##### Model
#### Variance of our random effect
### Task 2: Life is sweet as honey
#### Wrangle and plot the data
#### Model formula
#### Fit the models
#### Model with our aggregated data
#### Describing our residuals
##### Calculate the residual sum of squares for the `bee_int_mod` model. Save it as `rss_int`.
##### Calculate the RSE for the `bee_int_mod` model.
#### Calculating our random effect variances
##### Overview
##### Unexplained variance after fitting the interaction model 
##### RSE for main effects model on aggregated data
##### Hive-to-hive variance
##### Summary of all our calculated error variances
#### Summary
##### Full interaction model (includes main effects) (`bee_int_mod`)
##### Main effects only model, on hive/song aggregated data (`bee_agg_mod`)
##### Intercept only model for hives averages (`bee_hive_mod`)
### Where to next?
### Credits
## Vocal pitch case study: Part 1  (LMMs)
### Motivation
### Design of the experiment
### Read in the data and explore it
### Recall: Linear regression assumptions
#### Why we can't assume independence
#### Let's start with a picture
##### Key themes from our plot
## Linear mixed models
### Thoughts on plots for hierarchical/correlated data generally
### Assumptions
### Our model set up
#### Our STA302 linear model
#### Linear mixed model
#### Alternative formulations
### What can correlated errors look like?
#### Random intercepts
#### Random slopes
#### Random slopes and intercepts
### How do we tell R which situation we're in?
#### Vignette activity
### Additional considerations
#### Linear mixed models come with lots of different names
#### Fixed vs. random effects
#### REML or ML {#reml}
#### Confidence intervals and tests
## Vocal pitch case study: Part 2
### Modelling individual means with random intercepts
#### Random intercept only model
#### What does this model do?
#### Interpreting this output
#### Adding our fixed effects
#### Model with condition and sex
#### Aside: Summary of means
#### Random slopes for condition
#### Scenario random intercepts
### Scenario random slopes
## Interactions between random effects and fixed effects
### Model formula
### How would we fit this with `lmer`?
#### Do we need the interaction?
## More fixed vs random effects practice
### Answers
#### Cockroaches
#### Radon
## Advice for polishing your writing

<!--chapter:end:22-module3.Rmd-->

# Module 4

<!--chapter:end:23-module4.Rmd-->

# Module 5

<!--chapter:end:24-module5.Rmd-->

# References {-}

<!--chapter:end:49-references.Rmd-->


# (PART\*) Appendix {-}
# Resources

Placeholder


## Course tools overview
### Admin
## Using RStudio with the JupyterHub
## Team Up!
### To participate in these activities, you **need**:
### **Before** the activity you should:
### Some rules/logistics
### Team Up! Instructions
#### Step 1: Decide on roles
#### Step 2: Driver sets up group
#### Step 3: Members join
#### Step 4: Complete the activity
#### Step 5: The Driver MUST click Submit to Quercus for your answers to be processed. 
## Zoom, Zoom, Zoom, Zoom... {#zoomzoomzoomzoom}
### Make sure your Zoom is up to date
### Customize!
### VPN
### Notes:
### Changing your profile picture on Zoom and Quercus
### What to do if you experience technical difficulties during class?
### What to do if your instructor or TA is experiencing technical difficulties on Zoom
## Student support services and resources
### Mental health support
### General University resources
### Financial support
### Arts & Science COVID19 FAQ

<!--chapter:end:50-resources.Rmd-->

# FAQs and Errata

## Frequently asked questions

While [Piazza](`r `piazza`) is our main class question and answer board, this page will have some static Questions and Answers for frequently asked questions. Use Cmd + F (Mac) or Ctrl + F (PC) to search for keywords on this page.

Additionally, make sure you're familiar with the [Syllabus](#syllabus). I've tried to explain as much as I could there.

### Course admin

#### STA303 pre-requisites {#prereq-faq}

##### *I didn't take STA302 or an equivalent course, can I still take STA303?*\
No, sorry. We enforce pre-reqs strictly. This isn't up to me. You will be removed from the course. Please **reach out to the UG stats team ([ug.statistics\@utoronto.ca](ug.statistics@utoronto.ca))** about questions of this nature.

-   [Book an appointment during their office hours](https://outlook.office365.com/owa/calendar/DepartmentofStatisticalSciencesUndergraduate@utoronto.onmicrosoft.com/bookings/ "https://outlook.office365.com/owa/calendar/DepartmentofStatisticalSciencesUndergraduate@utoronto.onmicrosoft.com/bookings/").

-   For grad courses, please email [grad.statistics\@utoronto.ca](mailto:grad.statistics@utoronto.ca).

#### Lecture and tutorial times

##### *How exactly do the tutorials and lectures work?*

__Wednesdays__: 1st part is (recorded) content/demo and the second is office hour (unrecorded). Aiming for half-half, but will vary.

__Thursdays__: The 1st Thursday of a module will have a Team Up! or other practice activity. This will also be made available asynchronously, but the knowledge basket points for a Team Up! can only be earned by __synchronous, group participation__. The 2nd Thursday will be drop-in TA office hours to get help on content and assessments. 

Thursday sessions are not recorded, but the Team Up! or other activities content will be made available to everyone. There are several other ways to earn your knowledge basket points if this doesn't suit your tech setup (e.g. no mic) or time zone.

#### Recorded lectures

##### *"Where can I find recorded lectures and how soon can I expect them to be available?"*

Recorded lectures will be linked on the [Course overview](`r course_overview`) page. I aim to have the links up within 24 hours of class. They take some time to process.

#### Sections

##### *"Do L0101 and L0201 cover the same materials?"*

Yes. The only difference is when your synchronous class is. See the below question in  "Attending synchronous class".

#### Attending synchronous class

##### *"Can I attend the synchronous class for the other section?"*

Yes!\*

\*If the number of attendees is getting too close to the call cap of 300 (this is a Zoom license thing), preference will be given to those enrolled in the session and others will be asked to leave. Any Team Up! activity bonuses will also be applied—section/session does not matter.

##### *"Why can't I access the class/office hour Zoom meeting?"*

You must have and be signed in with your University of Toronto Zoom account. Use the 'SSO' (single sign-on) option. More info and troubleshooting advice [here](#zoomzoomzoomzoom).

##### *"Will STA303/STA1002 be able to be completed online-only?"* 

Yes.

-   **STA303** will be a flipped course, with content delivered online and opportunities for activities both in-person (subject to health advice) and online. All assessments will be completed and submitted online.

-   If you are enrolled in an **in-person tutorial**, you will have an option to attend online instead.

-   Synchronous attendance is NOT required to pass this course, but being able to attend (online) synchronously at the times in the timetable may make things easier for you.

##### *"Where is your **office**?"*/*"Can I come see you in-person?"* 

At this stage, I cannot offer in-person office hours nor student meetings in my office. Drop-ins are not currently allowed for any instructors or TAs in Statistical Sciences, unless they have told you they have organized another meeting space for this purpose.

### Assessments FAQ

#### Knowledge basket FAQ

##### _"I don't really understand the knowledge basket, how will that work? Can we earn more than 5 marks?"_

The knowledge basket maxes out at 5%, otherwise I get in trouble for giving away too many "free" points. (I know, I wish.)

##### _"Can we do as many knowledge basket activities as we want in order to gain the full 5%?"_

Yes! But do try to plan ahead, as I won't be adding a bunch of make-up opportunities at the end...part of the goal is to incentivize personalized, regular participation in the course to create the best learning outcomes for you.

##### _"How fast will we receive grades back for the knowledge basket activities?"_

It will depend, but many should be fairly quick—a few days if autograded/based on completion. 1–2 weeks for professional development proposal and evidence & reflection.


##### _"I am not too sure what ‘pre-knowledge quiz: 80% or workshop’ is supposed to mean."_

If you score 80% or more on the pre-knowledge check, you automatically get 0.5% for doing it + 0.5% for a high score. If you do the check but get less than 80% you get 0.5% for completion, and can still get that additional 0.5% if you come participate in the workshop.

Workshop open to all. And you don't have to go if you have other plan for filling your basket. It is meant to be helpful to you, though. 

And no, you can't get the workshop AND 80%+ points. One or the other for a max of 1%.

##### _"What will additional opportunities like speaker series reflections be like?"_

May vary depending on the speaker/workshop, but for next week (grad panel) it will likely be attendance + a short Quercus survey. Just confirming a few things still so, TBA. (Watch for more details in announcements.)

##### _"Are the three phases of each writing assignment graded on completion?"_

Yes, but see caveats [here in the general instructions for the writing tasks.](https://sta303-bolton.github.io/sta303-w22-courseguide/knowledge-basket-writing-and-peer-feedback.html#general-instructions)


##### _"No questions, although seems to be a hectic course with a lot of minor deadlines."_

If you don't want lots of little deadlines, you don't have to have lots of little deadlines! Do the professional development tasks + a few Team Ups! or the professional development task + punctuation art. Throw in the pre-knowledge check and you're looking great! 

#### Portfolios FAQ

##### _"I am curious about the format of portfolio and assessment and how they will be conducted."_

2022-01-12: __More info over the next two weeks__, but these will be a lot like a traditional assignment, but with a writing task (the module writing tasks are good indicators and practice) and some additional narrative about what you're learning/demonstrating. You'll submit commented code in an Rmd and the associated PDF. 


#### Mixed assessments FAQ

##### _"How does the mixed assessment work? Is it like a midterm?"_

Mostly, except there will also be a small amount of pre-work. More information closer too, but the overall goal is to make it more real-world. When you prep for a big meeting in the real world, you might calculate some summary stats, have a few basic plots ready, have some notes, etc. Sure, there are some things where you'll have to think it through in the moment (in the mixed assessment and in the real world), but I hope having the untimed pre-work helps lessen some of the test anxiety folks can feel. Less mind reading, more targeted prep. 

##### _"What's the difference between mini and mixed assessments? Are they both term tests?"_

One is bigger and one is smaller. ;) But yeah, the mini has one 50 minute timed component while the main mixed assessment will have more pre-work and two 50 minute timed parts.

##### _Will we get some sample practice problems to work on before the mini-mixed and mixed assessments?_

The 'mini' is effectively practice problems for the main, but Team Up!s will also be useful practice for the mixed assessments. If there isn't a Team Up! (which you've be able to review asynchronously for study purposes) for a module I'll offer a practice quiz (no points) option or other practice activity.


##### _"What exactly will we do in assessment weeks?"_

There is __no new content or writing module__. They are a time to focus your 6–8 hours of weekly STA303 time on the assessment. __Mixed:__ doing the pre-work and the 100 minute (2 x 50) timed component. __Project week:__ working with your group/self, asking questions in office hours. The expectation is that you'll start the project well before then, but I know the end of the semester can be stressful and busy, so I'm making things as simple and focused for you as I can.


#### Final project FAQ

##### _"What kind of activities will the final project entail?"_

More details before reading week, but you will receive data and a client brief and be asked to create a written report that includes an executive summary as well as a more technical report.


#### Assessments: General FAQ

##### _"How we can choose path A or B for the marking scheme-- would this be on Quercus?"_

As long as you're okay with getting the higher of the two marks, I'll calculate your grade both ways and give you the higher one.

##### _"So are all assessment due on Thursday 3:03?"_

Almost all the big ones! The mixed assessments have a window, but professional development proposal, professional development evidence & reflection, mini-portfolio, portfolio and project are all due on a Thursday at 3:03 p.m.

##### _"Are we allowed to answer assignments with programming languages other than R?"_

This is an R-based course, so only coding assessments using R will be accepted. (Note: For the professional development task ONLY you could use another language in a blog post/write-up etc., as we are grading your goal-setting and reflection on a communication/collaboration task, not your code directly.)

##### _"What are the minimum requirements to pass the course?"_

50% overall, no special conditions.


### Team Up!

#### Troubleshooting & FAQ advice from U of T CTSI

[__Link to student facing Quercus Support resources__.](https://q.utoronto.ca/courses/46670/pages/integration-team-up-for-students)

##### *"My screen seems to be lagging compared to those of my group members (e.g., I'm not on the same question as the driver/members, the answer I chose does not appear on my group members' screens, etc.)"*

As long as you are logged in, you will receive your grade, so just continue to participate by communicating with your team. Almost always, your device will re-sync with the rest of your team's devices within a minute or two. If not, refresh your screen once. Repeatedly refreshing is not usually helpful!

##### *"I've been disconnected. Will my quiz progress be saved? Can I re-join my group?"*

Enter the Team Up! session again and you will automatically be put back into your group. Your progress will be saved, and you will return to the question you or your group was working on. This is true for the Driver as well as any team member.

##### *"How do I send my completed quiz results?"*

Click the large red "Submit to Quercus" button at the end of the Team Up! quiz.

##### *"Can we change our group driver?"*

You can request a driver change by pressing the red exclamation mark in the top right of your Team Up! quiz.

##### *"How is the driver for our group chosen, and how can the driver pass the group ID to others in remote classes?"*

Group members can decide who will be the Driver (ideally someone with a good internet connection). The Driver can pass the group ID to other members verbally through chat or microphone in breakout rooms.

##### *"The Driver of my group has to leave unexpectedly or their device has stopped functioning. How do we proceed with the quiz?"*

Request for a Driver Change using the red button at the top right of your Team Up! Session. This button only provides help for Driver Changes. You may also need to speak with your instructor or TA.

## Other

### References

##### *"Can you (Prof. Bolton) write me a reference?"*

Please read my personal policy [here](https://www.lizabolton.com/references.html) to get a sense of under what circumstances I could write for you, but basically, a good mark in one class is not sufficient and you need to have at least two 'activities' with me. [If you believe you meet my basic criteria, you can request a reference from me [here](https://forms.office.com/r/XHqjGXjCru).]{style="background-color: #FFD700"} I will then accept or decline based on the the information provided.

##### *"Do you (Prof. Bolton) have any research opportunities available?"*

**Research/work study/teaching assistant opportunities:**

-   See the [Department website](https://www.statistics.utoronto.ca/employment-opportunities/cupe-positions-unit-1 "https://www.statistics.utoronto.ca/employment-opportunities/cupe-positions-unit-1"). The main round of TA recruitment occurs during the summer but there are occasionally emergency postings.

-   Some information about opportunities with me on my [website](https://www.lizabolton.com/opportunities.html).

-   **Reading courses:** STA496/497: Readings in Statistics must be registered for as part of [special enrolment during July](https://utoronto.sharepoint.com/sites/ArtSci-STA/Undergrad/SitePages/Special-Enrolment-Courses--STA490Y1,-STA492H1-and-STA496H1-STA497H1.aspx "https://utoronto.sharepoint.com/sites/ArtSci-STA/Undergrad/SitePages/Special-Enrolment-Courses--STA490Y1,-STA492H1-and-STA496H1-STA497H1.aspx"). I will not be taking on any further students.

    -   If you're thinking about the future, I usually consider taking on a small number of STA497 students for a **half-credit, year long version.**

    -   There is much more information about my past students, research interests and what a course with me might be like on my website: [https://www.lizabolton.com/reading_courses.html](https://www.lizabolton.com/reading_courses.html)

## Errata

+----+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ID | Location                                 | Note                                                                                                                                                                                                                                                                                                                             |
+:===+:=========================================+:=================================================================================================================================================================================================================================================================================================================================+
| 1  | Module 1 Team Up!                        | See corrected [asynch answers](https://jupyter.utoronto.ca/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fsta303-bolton%2Fsta303-w22-activities&urlpath=shiny%2Fsta303-w22-activities%2Finst%2Ftutorials%2Fsta303_m1_teamup_asynch%2FSTA303_m1_teamup_synch.Rmd&branch=master). Marks were corrected for all groups. |
+----+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2  | HTML version of Syllabus in course guide | Mention of a different % for the knowledge basket for Path A. Both paths have a 5% cap.                                                                                                                                                                                                                                          |
+----+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3  | Mini-portfolio instructions              | There should be 6 columns, not 5 in the tibble `ci_vals`.                                                                                                                                                                                                                                                                        |
|    |                                          |                                                                                                                                                                                                                                                                                                                                  |
|    |                                          | `ci_vals`, tibble with ~~5~~ 6 columns (after all steps completed)                                                                                                                                                                                                                                                               |
+----+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4  | Portfolio instructions                   | There are 5 tasks total (some have sub parts).                                                                                                                                                                                                                                                                                   |
|    |                                          |                                                                                                                                                                                                                                                                                                                                  |
|    |                                          | In Task 5: Simulating *p* values, there are only 3 simulated datasets to make, `sim1`, `sim2`, `sim3`. A previous version of the instructions had 4 (I simplified the task from my original plan).\                                                                                                                              |
|    |                                          | \                                                                                                                                                                                                                                                                                                                                |
|    |                                          | Re-pulling the template through the template link will update your instruction document.                                                                                                                                                                                                                                         |
|    |                                          |                                                                                                                                                                                                                                                                                                                                  |
|    |                                          | Note: The mention of `sim4` in the `sim_desc` dataset IS intentional. Notice the instruction to "Make any alterations necessary to `all_sim` so that you can join on the dataset `sim_description` to provided better labels for each simulation (but without including any irrelevant labels)."                                 |
|    |                                          |                                                                                                                                                                                                                                                                                                                                  |
|    |                                          | Piazza: <https://piazza.com/class/kx47tj4fmy65dg?cid=212>                                                                                                                                                                                                                                                                        |
+----+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5  | Portfolio instructions                   | Task 2a) Missing fragments:                                                                                                                                                                                                                                                                                                      |
|    |                                          |                                                                                                                                                                                                                                                                                                                                  |
|    |                                          | "Use `kable` to display the table nicely and add an appropriate caption."                                                                                                                                                                                                                                                        |
|    |                                          |                                                                                                                                                                                                                                                                                                                                  |
|    |                                          | "`agg_mod`, a main effects model where `yield_avg_int` is the response and `patch` and `treatment` are the predictors. Use appropriate data aggregated across both `patch` and `treatment`."                                                                                                                                     |
|    |                                          |                                                                                                                                                                                                                                                                                                                                  |
|    |                                          | `var_ab`, variance in yield explained by the interaction between patch and treatment, after accounting for the fixed effects and other sources.                                                                                                                                                                                  |
|    |                                          |                                                                                                                                                                                                                                                                                                                                  |
|    |                                          | Piazza: <https://piazza.com/class/kx47tj4fmy65dg?cid=216>                                                                                                                                                                                                                                                                        |
+----+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

<!--chapter:end:51-faqs-plus.Rmd-->


# Bits and pieces

Placeholder


## Code to generate course art
## M1 supporting information on matrices (not assessed) {#matrices}
### Background
#### Some true things about matrices
### Example 
#### Classic regression, k-1 dummies (intercept)
#### Classic regression but trying to force k dummies (with an intercept)
### Regression NOT classic, actually ANOVA! (no intercept)
### Further reading (if you want it)
## _p_ values (recap)
### What if you get a value that is exactly one of these thresholds?

<!--chapter:end:52-appendix.Rmd-->


# Announcements summary

Placeholder


### Looking for student representatives for STA303 {#studentrep}
#### The role of a student representative
#### Benefits of being a student representative
#### How to become a rep
#### Eligibility criteria

<!--chapter:end:53-announcements.Rmd-->

